[package]
name = "snes_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
